<iframe
  width="1000"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=YOURKEY
    &q=Space+Needle,Seattle+WA">
</iframe>
