<iframe
  width="1000"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBORXGJ4TErl-3S5cDG5pb0sfNXoU9S8vg
    &q=Space+Needle,Seattle+WA">
</iframe>
